version: "3"                                                # docker-compose 버전이다
services:                                                   
    nginx:                                                  # 서비스명
        nginx:1.17.10                                       # nginx:1.17.10 이미지를 사용
        container_name: ng01                                # 컨테이너명
        ports:                                              # 포트 개방 "hostPort:dockerPort"으로 포워딩한다
            - "80:80"                                       
        volumes:                                            # 볼륨 마운트. 호스트의 파일을 사용하려면 필요하다
            - ./src:/src                                    # 소스코드 마운트
            - ./nginx.conf:/etc/nginx/conf.d/default.conf # nginx 세팅 마운트
        depends_on:                                         # 'web'컨테이너가 구동되어야만 실행된다
            - web                                           

    web:                                                    
        build: .                                            # 메인으로 빌드될 Dockerfile을 적는다. 지금은 현재 폴더에 있다고 알린다
        container_name: dg01                                
        command: bash -c "                                  # Dockerfile을 빌드 후 실행했을때 자동으로 입력되는 명령어다
            python3 manage.py collectstatic --no-input &&   # collectstatic을 실행했을때 기존에 이미 파일이 있는 경우 그래도 실행하냐고 물어본다. 이 때 입력을 방지하기 위해 --no-input 옵션을 사용한다
            python3 manage.py makemigrations &&             
            python3 manage.py migrate &&                    
            gunicorn project.wsgi:application -b 0:80"      # Django의 일반적인 runserver가 아닌 gunicorn을 사용해서 서버를 구동한다. 포트는 0.0.0.0:80으로 바인딩한다. 모든 아이피에서의 접속을 허용하고 80번 포트를 연다는 의미
        depends_on:                                         
            - db                                            
        volumes:                                            
            - ./src:/src                                    

    db:                                                     
        image: postgres:12.2                                
        container_name: ps01                                
        environment:                                        # PostgreSQL의 환경설정이다.
            POSTGRES_DB: db                                 
            POSTGRES_USER: admin                            
            POSTGRES_PASSWORD: admin