version: "3"

services:
  nginx:
    image: nginx:1.17.10
    container_name: ng01
    ports:
      - "80:80"
    volumes:
      - ./src:/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

  web:
    build: .
    container_name: dg01
    command: >
      bash -c "python manage.py collectstatic --no-input &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      gunicorn project.wsgi:application -b 0:80"
    depends_on:
      - db
    volumes:
      - ./src:/src

  db:
    image: postgres:12.2
    container_name: ps01
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
