version: "3"  # docker-compose 버전

services:
  nginx:  # 서비스명
    image: nginx:1.17.10  # nginx:1.17.10 이미지를 사용
    container_name: ng01  # 컨테이너명
    ports:
      - "80:80"  # 포트 개방 "hostPort:dockerPort"으로 포워딩
    volumes:
      - ./src:/src  # 소스코드 마운트
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # nginx 설정 파일 마운트
    depends_on:
      - web  # 'web'컨테이너가 구동되어야만 실행됨

  web:
    build: .  # 메인으로 빌드될 Dockerfile이 현재 폴더에 있음
    container_name: dg01
    command: >-  # 여러 명령을 한 줄로 표현
      bash -c "
      python3 manage.py collectstatic --no-input &&
      python3 manage.py makemigrations &&
      python3 manage.py migrate &&
      gunicorn project.wsgi:application -b 0:80"
    depends_on:
      - db
    volumes:
      - ./src:/src

  db:
    image: postgres:12.2
    container_name: ps01
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
